apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bd-sts
  namespace: name2
  labels:
    app: bd-sts
spec:
  selector:
    matchLabels:
      app: bd-sts
  serviceName: bd-server
  template:
    metadata:
      labels:
        app: bd-sts
    spec:
      containers:
        - name: bd-server
          image: efajardolopez/bd-server
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bd-svc-headless
  namespace: name2
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    app: bd-sts
#bd-svc-headless.app.svc.cluster.local
