apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-pod
  namespace: name1
  labels:
    app: rs-pod
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - image: efajardolopez/api-persona
          name: api-persona
          ports:
            - containerPort: 8080
              protocol: TCP
        - image: efajardolopez/api-preferencia
          name: api-preferencia
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
